# Generated by Django 2.2 on 2020-05-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='ss_goods',
        ),
        migrations.AlterModelTable(
            name='goodsimage',
            table='ss_goods_image',
        ),
        migrations.AlterModelTable(
            name='goodssku',
            table='ss_goods_sku',
        ),
        migrations.AlterModelTable(
            name='goodstype',
            table='ss_goods_type',
        ),
        migrations.AlterModelTable(
            name='indexgoodsbanner',
            table='ss_index_banner',
        ),
        migrations.AlterModelTable(
            name='indexpromotionbanner',
            table='ss_index_promotion',
        ),
        migrations.AlterModelTable(
            name='indextypegoodsbanner',
            table='ss_index_type_goods',
        ),
    ]
