# Generated by Django 2.2 on 2020-05-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='ss_address',
        ),
        migrations.AlterModelTable(
            name='user',
            table='ss_user',
        ),
    ]
