# Generated by Django 2.2 on 2020-05-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200507_1124'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordergoods',
            table='ss_order_goods',
        ),
        migrations.AlterModelTable(
            name='orderinfo',
            table='ss_order_info',
        ),
    ]
